actuators:
  - package: dynamixel_x_controller
    class: Dynamixel_X::Dynamixel_X_Actuator_Config_Parser
    config:
      camera_joint_actuator:
        servo_id: 1
        controller_name: camera_joint_controller
        # zero_deg: 0.0
        cw_limit_deg: -180.0
        ccw_limit_deg: 180.0
        max_effort_value: 1000.0

controllers:
  - package: dynamixel_x_controller
    class: Dynamixel_X::Dynamixel_X_Controller_Config_Parser
    config:
      camera_joint_controller:
        controller_id: 1
        port: /dev/camera_u2d2
        baud_rate: 57600