joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

camera_joint_controller:
    type: position_controllers/JointPositionController
    joint: camera_tilt_joint